#!/usr/bin/with-contenv bash

if [ -S /var/run/docker.sock ]; then
    GID=$(/usr/bin/stat --printf="%g" /var/run/docker.sock 2>/dev/null)
    if [ -n "$GID" ]; then
        /usr/sbin/groupmod -g $GID docker
        /usr/sbin/addgroup abc docker
    fi
fi
